version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:8080
    environment:
      - REDIS_URL=redis://redis:6379/0
  redis:
    image: redis:latest
