version: '2'
services:
  web:
    image: kakakikikeke/memo:ver_golang_for_vch
    ports:
      - 80:8080
    links:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379/0
    labels:
      kompose.service.type: LoadBalancer
  redis:
    image: redis:latest